In [138]:
# installing pandas for opening the csv file

import pandas as pd

# open the csv to a variable

schedule_data = pd.read_csv('SCHEDULER.csv')

# read the csv file using pandas
schedule_data

,S.NO,DATE,START,END,DURATION,SUBJECT,Unnamed: 6,Unnamed: 7,S.NO.1,WISH LIST
0,1,10/07/22,13:54:00,14:54:30,01:00:30,Python-Django,NaN,NaN,1.0,download a travel page and run it through django
1,2,10/07/22,16:59:02,17:58:10,00:59:08,Python-Django,NaN,NaN,2.0,enumeration in python
2,3,10/07/22,18:29:08,21:31:58,03:02:50,Python-Django,NaN,NaN,3.0,edit color of you tube videos
3,4,11/07/22,05:48:05,07:30:00,01:41:55,Python-Django,NaN,NaN,4.0,django web app login and logout with bank balance
4,5,11/07/22,19:34:33,21:57:31,02:22:58,Python-Django,NaN,NaN,5.0,create bancs application
...,...,...,...,...,...,...,...,...,...,...
106,107,04/09/22,09:05:00,09:10:28,00:05:28,Python Projects,NaN,NaN,NaN,NaN
107,108,04/09/22,14:03:10,15:08:48,01:05:38,CS50 – Data Structures,NaN,NaN,NaN,NaN
108,109,04/09/22,16:46:00,17:17:21,00:31:20,CS50 – Data Structures,NaN,NaN,NaN,NaN
109,110,04/09/22,19:50:27,20:10:00,00:19:32,Open CV,NaN,NaN,NaN,NaN
110,111,04/09/22,21:00:22,NaN,-21:00:23,Python Projects,NaN,NaN,NaN,NaN

In [139]:


# converting date into a week day

# getting date column

date_column = schedule_data['DATE']

date_column

0      10/07/22
1      10/07/22
2      10/07/22
3      11/07/22
4      11/07/22
         ...
106    04/09/22
107    04/09/22
108    04/09/22
109    04/09/22
110    04/09/22
Name: DATE, Length: 111, dtype: object

In [140]:
# storing the unique dates in a variable 
coding_dates = date_column.unique()

coding_dates

array(['10/07/22', '11/07/22', '12/07/22', '13/07/22', '14/07/22',
       '15/07/22', '16/07/22', '17/07/22', '18/07/22', '21/07/22',
       '22/07/22', '23/07/22', '24/07/22', '25/07/22', '26/07/22',
       '27/07/22', '28/07/22', '29/07/22', '30/07/22', '31/07/22',
       '01/08/22', '02/08/22', '03/08/22', '04/08/22', '05/08/22',
       '06/08/22', '07/08/22', '08/08/22', '24/08/22', '25/08/22',
       '26/08/22', '27/08/22', '28/08/22', '29/08/22', '30/08/22',
       '31/08/22', '01/09/22', '02/09/22', '03/09/22', '04/09/22'],
      dtype=object)

In [141]:



last = '05/09/2022'

day = {
0 : 'Sunday',
1 : 'Monday',
2 : 'Tuesday',
3 : 'Wednesday',
4 : 'Thrusday',
5 : 'Friday',
6 : 'Saturday',}

my_dict = {}

my_date = []

my_day = []

for i in range(7,10):
    v = -1
    for j in range(1, 32):
        if (j < 10 and i == 7) or (j > 4 and i == 9):
            continue 

        

        if (j < 10):
            v += 1
            print(f'0{j}/0{i}/2022 - {day[v%7]}')
            my_date.append(f'0{j}/0{i}/22')
            my_day.append(day[v%7])
           
        else:  
            v += 1  
            print(f'{j}/0{i}/2022 - {day[v%7]}')
            my_date.append(f'{j}/0{i}/22')
            my_day.append(day[v%7])

10/07/2022 - Sunday
11/07/2022 - Monday
12/07/2022 - Tuesday
13/07/2022 - Wednesday
14/07/2022 - Thrusday
15/07/2022 - Friday
16/07/2022 - Saturday
17/07/2022 - Sunday
18/07/2022 - Monday
19/07/2022 - Tuesday
20/07/2022 - Wednesday
21/07/2022 - Thrusday
22/07/2022 - Friday
23/07/2022 - Saturday
24/07/2022 - Sunday
25/07/2022 - Monday
26/07/2022 - Tuesday
27/07/2022 - Wednesday
28/07/2022 - Thrusday
29/07/2022 - Friday
30/07/2022 - Saturday
31/07/2022 - Sunday
01/08/2022 - Sunday
02/08/2022 - Monday
03/08/2022 - Tuesday
04/08/2022 - Wednesday
05/08/2022 - Thrusday
06/08/2022 - Friday
07/08/2022 - Saturday
08/08/2022 - Sunday
09/08/2022 - Monday
10/08/2022 - Tuesday
11/08/2022 - Wednesday
12/08/2022 - Thrusday
13/08/2022 - Friday
14/08/2022 - Saturday
15/08/2022 - Sunday
16/08/2022 - Monday
17/08/2022 - Tuesday
18/08/2022 - Wednesday
19/08/2022 - Thrusday
20/08/2022 - Friday
21/08/2022 - Saturday
22/08/2022 - Sunday
23/08/2022 - Monday
24/08/2022 - Tuesday
25/08/2022 - Wednesday
26/08/2022 - Thrusday
27/08/2022 - Friday
28/08/2022 - Saturday
29/08/2022 - Sunday
30/08/2022 - Monday
31/08/2022 - Tuesday
01/09/2022 - Sunday
02/09/2022 - Monday
03/09/2022 - Tuesday
04/09/2022 - Wednesday

In [142]:
for i in range(len(my_date)):
    my_dict[my_date[i]] = my_day[i]

In [143]:
my_dict

{'10/07/22': 'Sunday',
 '11/07/22': 'Monday',
 '12/07/22': 'Tuesday',
 '13/07/22': 'Wednesday',
 '14/07/22': 'Thrusday',
 '15/07/22': 'Friday',
 '16/07/22': 'Saturday',
 '17/07/22': 'Sunday',
 '18/07/22': 'Monday',
 '19/07/22': 'Tuesday',
 '20/07/22': 'Wednesday',
 '21/07/22': 'Thrusday',
 '22/07/22': 'Friday',
 '23/07/22': 'Saturday',
 '24/07/22': 'Sunday',
 '25/07/22': 'Monday',
 '26/07/22': 'Tuesday',
 '27/07/22': 'Wednesday',
 '28/07/22': 'Thrusday',
 '29/07/22': 'Friday',
 '30/07/22': 'Saturday',
 '31/07/22': 'Sunday',
 '01/08/22': 'Sunday',
 '02/08/22': 'Monday',
 '03/08/22': 'Tuesday',
 '04/08/22': 'Wednesday',
 '05/08/22': 'Thrusday',
 '06/08/22': 'Friday',
 '07/08/22': 'Saturday',
 '08/08/22': 'Sunday',
 '09/08/22': 'Monday',
 '10/08/22': 'Tuesday',
 '11/08/22': 'Wednesday',
 '12/08/22': 'Thrusday',
 '13/08/22': 'Friday',
 '14/08/22': 'Saturday',
 '15/08/22': 'Sunday',
 '16/08/22': 'Monday',
 '17/08/22': 'Tuesday',
 '18/08/22': 'Wednesday',
 '19/08/22': 'Thrusday',
 '20/08/22': 'Friday',
 '21/08/22': 'Saturday',
 '22/08/22': 'Sunday',
 '23/08/22': 'Monday',
 '24/08/22': 'Tuesday',
 '25/08/22': 'Wednesday',
 '26/08/22': 'Thrusday',
 '27/08/22': 'Friday',
 '28/08/22': 'Saturday',
 '29/08/22': 'Sunday',
 '30/08/22': 'Monday',
 '31/08/22': 'Tuesday',
 '01/09/22': 'Sunday',
 '02/09/22': 'Monday',
 '03/09/22': 'Tuesday',
 '04/09/22': 'Wednesday'}

In [144]:
print(my_dict[coding_dates[2]])

Tuesday

In [145]:
for i in range(len(coding_dates)):
    print(f'{coding_dates[i]} -- {my_dict[coding_dates[i]]}')

10/07/22 -- Sunday
11/07/22 -- Monday
12/07/22 -- Tuesday
13/07/22 -- Wednesday
14/07/22 -- Thrusday
15/07/22 -- Friday
16/07/22 -- Saturday
17/07/22 -- Sunday
18/07/22 -- Monday
21/07/22 -- Thrusday
22/07/22 -- Friday
23/07/22 -- Saturday
24/07/22 -- Sunday
25/07/22 -- Monday
26/07/22 -- Tuesday
27/07/22 -- Wednesday
28/07/22 -- Thrusday
29/07/22 -- Friday
30/07/22 -- Saturday
31/07/22 -- Sunday
01/08/22 -- Sunday
02/08/22 -- Monday
03/08/22 -- Tuesday
04/08/22 -- Wednesday
05/08/22 -- Thrusday
06/08/22 -- Friday
07/08/22 -- Saturday
08/08/22 -- Sunday
24/08/22 -- Tuesday
25/08/22 -- Wednesday
26/08/22 -- Thrusday
27/08/22 -- Friday
28/08/22 -- Saturday
29/08/22 -- Sunday
30/08/22 -- Monday
31/08/22 -- Tuesday
01/09/22 -- Sunday
02/09/22 -- Monday
03/09/22 -- Tuesday
04/09/22 -- Wednesday